apiVersion: v1
kind: Service
metadata:
  name: task-service
  labels:
    app: microservice-task
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: microservice-task
