apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    app: eureka
