server:
  port: 8082  # Let the server pick a random port
logging:
  level:
    root: INFO
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/m321
    username: m321
    password: m321
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/