spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://config-server:8888 # Corrected the config server URL
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Use Eureka for service discovery
